#!/bin/bash
#verilator -cc --top-module  msftDvIp_cheri_arty7_fpga -exe tb.cc --trace -F all.f 
export DesignRoot=../..
export VeriRoot=$DesignRoot/sim/verilator
verilator -cc --top-module  swci_vtb -exe $VeriRoot/stdin_main.cc --trace -f $VeriRoot/all.f 
