#!/bin/bash

VlogDef1=""
VlogDef2=""
VlogDef3=""
FileList="all.ibex.f"

# Loop over args
for arg in "$@"; do
  case "$arg" in
    -conf1) 
      VlogDef1="+define+CoreConfig1" ;;
    -conf2) 
      VlogDef1="+define+CoreConfig2" 
      FileList="all.kudu.f"
      ;;
    -rv32)  VlogDef2="+define+ForceRV32" ;;
    -trace) VlogDef3="+define+RVFI=1" ;;
    *)
      echo "Warning: Unknown option $arg" >&2
      ;;
  esac
done

VlogDefs="$VlogDef1 $VlogDef2 $VlogDef3"
echo "VlogDefs=$VlogDefs  FileList=$FileList"

rm -rf obj_dir
export DesignRoot=../..
#verilator --version
verilator -cc --timing --top-module  swci_vtb -exe ./swci_main.cc --trace $VlogDefs  -f $FileList 
