+define+RVFI
+incdir+$DesignRoot/cheriot-ibex/rtl/
+incdir+$DesignRoot/cheriot-ibex/vendor/lowrisc_ip/ip/prim/rtl
+incdir+$DesignRoot/cheriot-ibex/vendor/lowrisc_ip/dv/sv/dv_utils
+incdir+$DesignRoot/src/msft_cheri_subsystem/
$DesignRoot/cheriot-ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_ram_1p_pkg.sv
$DesignRoot/cheriot-ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_cipher_pkg.sv
$DesignRoot/cheriot-ibex/rtl/cheri_pkg.sv
$DesignRoot/cheriot-ibex/rtl/ibex_pkg.sv
$DesignRoot/cheriot-ibex/rtl/ibex_tracer_pkg.sv
$DesignRoot/cheriot-ibex/rtl/cheri_decoder.sv
$DesignRoot/cheriot-ibex/rtl/cheri_ex.sv
$DesignRoot/cheriot-ibex/rtl/cheri_regfile.sv
$DesignRoot/cheriot-ibex/rtl/cheri_trvk_stage.sv
$DesignRoot/cheriot-ibex/rtl/cheri_tbre.sv
$DesignRoot/cheriot-ibex/rtl/cheri_stkz.sv
$DesignRoot/cheriot-ibex/rtl/cheri_tbre_wrapper.sv
$DesignRoot/cheriot-ibex/rtl/ibex_fetch_fifo.sv
$DesignRoot/cheriot-ibex/rtl/ibex_prefetch_buffer.sv
$DesignRoot/cheriot-ibex/rtl/ibex_branch_predict.sv
$DesignRoot/cheriot-ibex/rtl/ibex_compressed_decoder.sv
$DesignRoot/cheriot-ibex/rtl/ibex_if_stage.sv
$DesignRoot/cheriot-ibex/rtl/ibex_controller.sv
$DesignRoot/cheriot-ibex/rtl/ibex_decoder.sv
$DesignRoot/cheriot-ibex/rtl/ibex_id_stage.sv
$DesignRoot/cheriot-ibex/rtl/ibex_load_store_unit.sv
$DesignRoot/cheriot-ibex/rtl/ibex_wb_stage.sv
$DesignRoot/cheriot-ibex/rtl/ibex_alu.sv
$DesignRoot/cheriot-ibex/rtl/ibex_multdiv_fast.sv
$DesignRoot/cheriot-ibex/rtl/ibex_multdiv_slow.sv
$DesignRoot/cheriot-ibex/rtl/ibex_ex_block.sv
$DesignRoot/cheriot-ibex/rtl/ibex_csr.sv
$DesignRoot/cheriot-ibex/rtl/ibex_cs_registers.sv
$DesignRoot/cheriot-ibex/rtl/ibex_counter.sv
$DesignRoot/cheriot-ibex/rtl/ibex_dummy_instr.sv
$DesignRoot/cheriot-ibex/rtl/ibex_core.sv
$DesignRoot/cheriot-ibex/rtl/ibex_pmp.sv
$DesignRoot/cheriot-ibex/rtl/ibexc_top.sv
$DesignRoot/cheriot-ibex/rtl/ibex_tracer.sv
$DesignRoot/cheriot-ibex/rtl/ibexc_top_tracing.sv
$DesignRoot/cheriot-ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_fifo_async.sv
$DesignRoot/src/msft_cheri_core/msftDvIp_obimux3.sv
$DesignRoot/src/msft_cheri_core/msftDvIp_obimux3w0.sv
$DesignRoot/src/msft_cheri_core/msftDvIp_riscv_cheri_debug_reg.sv
$DesignRoot/src/msft_cheri_core/msftDvIp_riscv_cheri_debug_rom.sv
$DesignRoot/src/msft_cheri_core/msftDvIp_riscv_cheri_debug.sv
$DesignRoot/src/msft_cheri_core/msftDvIp_riscv_cheri_dmibus.sv
$DesignRoot/src/msft_cheri_core/msftDvIp_riscv_cheri_mem.sv
$DesignRoot/src/msft_cheri_core/msftDvIp_cheri_core_wrapper.sv
$DesignRoot/src/msft_cheri_core/msftDvIp_cheri_core0.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_mmreg.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_plic.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_clint_tmr.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_tcdev_wrapper.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_axi_fifo.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_axi_mem_bit_write.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_axi_mgr_ifc.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_axi_sub_ifc.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_cheri_axi_fabric.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_creg_intc.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_creg_timer.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_dma_ctrl0.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_dma_engine.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_dma_fifo.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_dmb_fifo.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_dmb.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_fpga_block_ram_2port_model.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_fpga_block_ram_byte_wr_model.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_fpga_block_ram_model.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_gpio.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_i2c_1m_1s.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_i2c_fifo.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_i2c_mgr.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_i2c_sub.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_jtag_driver.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_msftDvIp_cheri_axi_fabric_addr_decode.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_msftDvIp_cheri_axi_fabric_mgr_mux.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_msftDvIp_cheri_axi_fabric_sub_mux.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_periph_axi2apb_decode_decoder.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_periph_axi2apb_decode.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_periph_wrapper_v0.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_riscv_memory_v0.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_spi_1m_1s.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_spi_fifo.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_spi_mgr.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_spi_sub.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_uart_fifo.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_uart.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvDebug_backdoor_v0.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvDebug_cpu_trace.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_axi2apb.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_axi_def_sub.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_axi_dma_apb.sv
$DesignRoot/src/msft_cheri_subsystem/msftDvIp_cheri0_subsystem.sv
$DesignRoot/src/msft_cheri_arty7/BUFG.v
$DesignRoot/src/msft_cheri_arty7/IBUF.v
$DesignRoot/src/msft_cheri_arty7/IOBUF.v
$DesignRoot/src/msft_cheri_arty7/OBUF.v
$DesignRoot/src/msft_cheri_arty7/PULLDOWN.v
$DesignRoot/src/msft_cheri_arty7/PULLUP.v
$DesignRoot/src/msft_cheri_arty7/msftDvDebug_jtag2AxiApb_pkg.sv
$DesignRoot/src/msft_cheri_arty7/msftDvIp_mmcm_arty7_0.sv
$DesignRoot/src/msft_cheri_arty7/msftDvIp_mmcm_arty7_1.sv
$DesignRoot/src/msft_cheri_arty7/msftDvIp_led_alive.sv
$DesignRoot/src/msft_cheri_arty7/msftDvDebug_sync_pulse_gen.sv
$DesignRoot/src/msft_cheri_arty7/msftDvDebug_globals.sv
$DesignRoot/src/msft_cheri_arty7/msftDvDbug_apb_mux.sv
$DesignRoot/src/msft_cheri_arty7/msftDvDebug_apb_mgr_sm.sv
$DesignRoot/src/msft_cheri_arty7/msftDvDebug_jtag_tap.sv
$DesignRoot/src/msft_cheri_arty7/msftDvDebug_jtag2AxiApb.sv
$DesignRoot/src/msft_cheri_arty7/msftDvDebug_spiSlave.sv
$DesignRoot/src/msft_cheri_arty7/msftDvDebug_i2c_sub_base.sv
$DesignRoot/src/msft_cheri_arty7/msftDvDebug_i2c_sub.sv
$DesignRoot/src/msft_cheri_arty7/msftDvDebug_apb_mux.sv
$DesignRoot/src/msft_cheri_arty7/msftDvDebug_v1.sv
$DesignRoot/src/msft_cheri_arty7/prim_flop_2sync.sv
$DesignRoot/src/msft_cheri_arty7/eth_mac_lite.sv
$DesignRoot/src/msft_cheri_arty7/msftDvIp_cheri_arty7_fpga.sv
./MMCME2_ADV.v
./glbl.v
./fpga_tb.sv
