#!/usr/local/bin/bash
#
VlogDef1=""
VlogDef2=""
VlogDef3=""
FileList="all.ibex.f"

# Loop over args
for arg in "$@"; do
  case "$arg" in
    -conf1) 
      VlogDef1="+define+CoreConfig1" ;;
    -conf2) 
      VlogDef1="+define+CoreConfig2" 
      FileList="all.kudu.f"
      ;;
    -rv32)  VlogDef2="+define+ForceRV32" ;;
    -nowave) VlogDef3="+define+NoWave" ;;
    *)
      echo "Warning: Unknown option $arg" >&2
      ;;
  esac
done

VlogDefs="$VlogDef1 $VlogDef2 $VlogDef3"
echo "VlogDefs=$VlogDefs  FileList=$FileList"

export DesignRoot=../..
rm simv.daidir/.vcs.timestamp
vcs -full64 -sverilog -xlrm uniq_prior_final +systemverilogext+sv +lint=TFIPC-L -timescale=1ns/1ps -debug_acc+all $VlogDefs -f $FileList
